"""Ways to use credit pools."""

PLAY_OPERATION = 0
INSTALL_ASSET_AGENDA = 1
ADVANCE_ASSET_AGENDA = 2
ADVANCE_ICE = 3
PERFORM_TRACE = 4
REZ_ICE = 5
REMOVE_TAGS = 6
INSTALL_HARDWARE = 7
TRASH_CARDS = 8
RUNS_ON_HQ = 9
INSTALL_PROGRAMS = 10
ADVANCE_CARDS_IN_SAME_SERVER = 11
USE_DECODERS = 12
INSTALL_VIRUSES = 13
USE_HOSTED = 14
PLAY_EVENT = 15
USE_ICEBREAKERS = 16
